### ISSUE TITLE
더보기 버튼 드롭다운 메뉴 추가

### ISSUE THREAD

**Issue by jay-noncelab** [noncelab/coconut_vault#10]
# 🚀 Feature -  홈 화면 개선

### 📝 Description

---

- [Task-699] 홈 화면 앱바 더보기 버튼 클릭시 드롭다운 메뉴가 보여지고 사용자가 이를 선택할 수 있도록 지원
- [Task-704] 지갑 목록이 비워있는져 있는 경우 홈 화면에 지갑 `바로 추가하기` 버튼 추가

### ✅ To Do List

---

####Task-699
- [x] 드롭다운 위젯 추가
- [x] `니모닉 문구 단어집`, `설정`, `앱 정보 보기`를 드롭다운 메뉴에 추가
- [x] 설정 팝업에서 `니모닉 문구 단어집`, `앱 정보 보기` 삭제

#### Task-704
- [x] 홈 화면 지갑 `바로 추가하기` 버튼 추가

### 📚Etc

---
